Repository 4math/Engine, pull requests merged in 2019-03, with the labels that each got.

#4 Added missing arguments to main function
  Engine/src/Main.cpp
Labels: enhancement

#6 Added module main headers
  Engine/src/graphics/GraphicsMain.h
  Engine/src/input/InputMain.h
  Engine/src/sound/SoundMain.h
Labels: enhancement

#8 Added Engine class
  Engine/src/EngineMain.cpp
  Engine/src/EngineMain.h
Labels: enhancement

#10 Feature engine main enhancement
  Engine/src/EngineMain.cpp
  Engine/src/EngineMain.h
  Engine/src/Main.cpp
Labels: enhancement

#14 Added sound module to EngineMain
  Engine/src/EngineMain.cpp
Labels: enhancement

#15 Added method to change global sound volume
  Engine/src/sound/SoundMain.cpp
  Engine/src/sound/SoundMain.h
Labels: enhancement

#17 Feature generic game class
  Engine/Engine.vcxproj
  Engine/Engine.vcxproj.filters
  Engine/src/GenericGame.h
Labels: Type: Enhancement

#18 Added m_game_name to GenericGame class
  Engine/src/GenericGame.h
Labels: Priority: Low, Status: Completed, Type: Enhancement

#20 Feature graphics
  Engine/Engine.vcxproj
  Engine/Engine.vcxproj.filters
  Engine/src/EngineMain.cpp
  Engine/src/EngineMain.h
  Engine/src/graphics/GraphicsMain.cpp
  Engine/src/graphics/GraphicsMain.h
  Engine/src/graphics/environment/EnvironmentMain.cpp
  Engine/src/graphics/environment/EnvironmentMain.h
Labels: Priority: Critical, Status: In Progress, Type: Enhancement

#21 fixed non-working code
  Engine/src/EngineMain.cpp
Labels: Priority: Critical, Type: Bug

#22 Fixed typo in code
  Engine/src/graphics/GraphicsMain.h
Labels: Priority: Low, Status: Completed, Type: Enhancement

#23 Fixed typo in code
  Engine/src/graphics/GraphicsMain.cpp
  Engine/src/graphics/GraphicsMain.h
Labels: Priority: Low, Status: Completed, Type: Enhancement

#24 Enhanced window creation code
  Engine/src/graphics/GraphicsMain.cpp
  Engine/src/graphics/environment/EnvironmentMain.cpp
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#25 Refactoring environment architecture changes
  Engine/Engine.vcxproj
  Engine/Engine.vcxproj.filters
  Engine/src/EngineMain.cpp
  Engine/src/EngineMain.h
  Engine/src/environment/EnvironmentMain.cpp
  Engine/src/environment/EnvironmentMain.h
  Engine/src/environment/InputMain.h
  Engine/src/graphics/GraphicsMain.cpp
  Engine/src/graphics/GraphicsMain.h
  Engine/src/graphics/environment/EnvironmentMain.cpp
  Engine/src/graphics/environment/EnvironmentMain.h
  Engine/src/sound/SoundMain.h
Labels: Priority: High, Status: Completed, Type: Enhancement

#26 Bugfix, removed ability to create windows with NO_WINDOW type
  Engine/src/environment/EnvironmentMain.cpp
Labels: Priority: Low, Status: Completed, Type: Bug

#27 Added input management system
  Engine/Engine.vcxproj
  Engine/Engine.vcxproj.filters
  Engine/src/EngineMain.cpp
  Engine/src/GenericGame.h
  Engine/src/environment/EnvironmentMain.cpp
  Engine/src/environment/EnvironmentMain.h
  Engine/src/environment/InputMain.cpp
  Engine/src/environment/InputMain.h
Labels: Priority: High, Status: Completed, Type: Enhancement

#28 Changed building result and temp. file directory location
  Engine/Engine.vcxproj
Labels: Priority: Low, Status: Completed, Type: Enhancement

#29 Improved virtual inheritance, fixed minor environment constructor bug
  Engine/src/EngineMain.cpp
  Engine/src/EngineMain.h
  Engine/src/GenericGame.h
  Engine/src/Main.cpp
  Engine/src/environment/EnvironmentMain.cpp
Labels: Priority: High

#30 Imporved base graphics class, added BeginFrame and EndFrame declarations
  Engine/src/graphics/GraphicsMain.cpp
  Engine/src/graphics/GraphicsMain.h
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#31 Enhanced code, improved abstraction
  Engine/src/EngineMain.cpp
  Engine/src/EngineMain.h
  Engine/src/GenericGame.h
  Engine/src/environment/EnvironmentMain.cpp
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#32 Initializing Vulkan
  Engine/Engine.vcxproj
  Engine/Engine.vcxproj.filters
  Engine/src/graphics/GraphicsMain.cpp
  Engine/src/graphics/GraphicsMain.h
  Engine/src/graphics/GraphicsUtils.cpp
  Engine/src/graphics/GraphicsUtils.h
Labels: Priority: High, Status: Completed, Type: Enhancement
