Repository 4math/Engine, pull requests merged in 2019-04, with the labels that each got.

#34 Feature validation layers
  Engine/src/graphics/GraphicsMain.cpp
  Engine/src/graphics/GraphicsMain.h
  Engine/src/graphics/GraphicsUtils.cpp
  Engine/src/graphics/GraphicsUtils.h
Labels: Priority: Medium, Type: Enhancement

#35 Refactored a bit of code, added FormatVkResult function
  Engine/src/graphics/GraphicsMain.cpp
  Engine/src/graphics/GraphicsUtils.cpp
  Engine/src/graphics/GraphicsUtils.h
Labels: Priority: Low, Status: Completed, Type: Enhancement

#36 Added CreateSurface method, refactored some code, enhanced some code …
  Engine/src/environment/EnvironmentMain.cpp
  Engine/src/environment/EnvironmentMain.h
  Engine/src/graphics/GraphicsMain.cpp
  Engine/src/graphics/GraphicsMain.h
  Engine/src/graphics/GraphicsUtils.cpp
  Engine/src/graphics/GraphicsUtils.h
Labels: Priority: High, Status: Completed, Type: Enhancement

#37 Smart pointers
  Engine/src/EngineMain.cpp
  Engine/src/EngineMain.h
  Engine/src/environment/EnvironmentMain.cpp
  Engine/src/environment/EnvironmentMain.h
  Engine/src/environment/InputMain.cpp
  Engine/src/graphics/GraphicsMain.h
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#38 Swap chain creation
  Engine/src/environment/EnvironmentMain.h
  Engine/src/graphics/GraphicsMain.cpp
  Engine/src/graphics/GraphicsMain.h
  Engine/src/graphics/GraphicsUtils.cpp
  Engine/src/graphics/GraphicsUtils.h
Labels: Priority: High

#39 Shader module creation
  Engine/Engine.vcxproj
  Engine/Engine.vcxproj.filters
  Engine/src/BasicShader.frag
  Engine/src/BasicShader.vert
  Engine/src/graphics/GraphicsMain.cpp
  Engine/src/graphics/GraphicsShaders.cpp
  Engine/src/graphics/GraphicsShaders.h
  Engine/src/graphics/GraphicsUtils.cpp
Labels: Priority: High
